import { SessionProvider } from 'next-auth/react';
import type { Metadata } from 'next';
import Navigation from '@/components/ui/navigation';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='antialiased'>
        <header>
          <Navigation />
        </header>
        <main>
          <SessionProvider>{children}</SessionProvider>
        </main>
        <footer className='fixed bottom-0 text-center w-full'>
          &#169; indicamp 2024
        </footer>
      </body>
    </html>
  );
}
